//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.LK.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SC.LK.Application.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор не найден!.
        /// </summary>
        internal static string AdminNotFound {
            get {
                return ResourceManager.GetString("AdminNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вас приветствует CTSoft Enterprise! На нашей платформе был создан аккаунт с использованием вашей почты. .
        /// </summary>
        internal static string CreateAccountEmailNoty {
            get {
                return ResourceManager.GetString("CreateAccountEmailNoty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить лицензию.
        /// </summary>
        internal static string FailedAddLicense {
            get {
                return ResourceManager.GetString("FailedAddLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось изменить данные! Попробуйте позже..
        /// </summary>
        internal static string FailedChangeData {
            get {
                return ResourceManager.GetString("FailedChangeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось создать билинг лицо! Попробуйте позже..
        /// </summary>
        internal static string FailedCreateBillingFace {
            get {
                return ResourceManager.GetString("FailedCreateBillingFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось создать конфигурацию! Попробуйте позже..
        /// </summary>
        internal static string FailedCreateConfigurations {
            get {
                return ResourceManager.GetString("FailedCreateConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось создать подразделение! Попробуйте позже..
        /// </summary>
        internal static string FailedCreateDivision {
            get {
                return ResourceManager.GetString("FailedCreateDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось создать шаблон! Попробуйте позже..
        /// </summary>
        internal static string FailedCreateTemplate {
            get {
                return ResourceManager.GetString("FailedCreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось создать пользователя! Попробуйте позже..
        /// </summary>
        internal static string FailedCreateUser {
            get {
                return ResourceManager.GetString("FailedCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить лицензию.
        /// </summary>
        internal static string FailedDeactivateLicense {
            get {
                return ResourceManager.GetString("FailedDeactivateLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить билинг лицо! Попробуйте позже..
        /// </summary>
        internal static string FailedDeleteBillingFace {
            get {
                return ResourceManager.GetString("FailedDeleteBillingFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить конфигурацию! Попробуйте позже..
        /// </summary>
        internal static string FailedDeleteConfigurations {
            get {
                return ResourceManager.GetString("FailedDeleteConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить подразделение! Попробуйте позже..
        /// </summary>
        internal static string FailedDeleteDivision {
            get {
                return ResourceManager.GetString("FailedDeleteDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить шаблон! Попробуйте позже..
        /// </summary>
        internal static string FailedDeleteTemplate {
            get {
                return ResourceManager.GetString("FailedDeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить терминал! Попробуйте позже..
        /// </summary>
        internal static string FailedDeleteTerminal {
            get {
                return ResourceManager.GetString("FailedDeleteTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить пользователя! Попробуйте позже..
        /// </summary>
        internal static string FailedDeleteUser {
            get {
                return ResourceManager.GetString("FailedDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить агентов.
        /// </summary>
        internal static string FailedGetAgentsByContragentId {
            get {
                return ResourceManager.GetString("FailedGetAgentsByContragentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить билинг лицо! Попробуйте позже..
        /// </summary>
        internal static string FailedGetBillingFace {
            get {
                return ResourceManager.GetString("FailedGetBillingFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить билинг лица! Попробуйте позже..
        /// </summary>
        internal static string FailedGetBillingFaces {
            get {
                return ResourceManager.GetString("FailedGetBillingFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить бизнес процесс.
        /// </summary>
        internal static string FailedGetBusinessProcess {
            get {
                return ResourceManager.GetString("FailedGetBusinessProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить конфигурацию! Попробуйте позже..
        /// </summary>
        internal static string FailedGetConfiguration {
            get {
                return ResourceManager.GetString("FailedGetConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить конфигурации! Попробуйте позже..
        /// </summary>
        internal static string FailedGetConfigurations {
            get {
                return ResourceManager.GetString("FailedGetConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить контрагента.
        /// </summary>
        internal static string FailedGetContractor {
            get {
                return ResourceManager.GetString("FailedGetContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить контрагентов пользовалеля! Попробуйте позже..
        /// </summary>
        internal static string FailedGetContractors {
            get {
                return ResourceManager.GetString("FailedGetContractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить подразделение! Попробуйте позже..
        /// </summary>
        internal static string FailedGetDivision {
            get {
                return ResourceManager.GetString("FailedGetDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить подразделениея! Попробуйте позже..
        /// </summary>
        internal static string FailedGetDivisions {
            get {
                return ResourceManager.GetString("FailedGetDivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить лицензию.
        /// </summary>
        internal static string FailedGetLicense {
            get {
                return ResourceManager.GetString("FailedGetLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить шаблон! Попробуйте позже..
        /// </summary>
        internal static string FailedGetTemplate {
            get {
                return ResourceManager.GetString("FailedGetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить шаблоны! Попробуйте позже..
        /// </summary>
        internal static string FailedGetTemplates {
            get {
                return ResourceManager.GetString("FailedGetTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить подразделение! Попробуйте позже..
        /// </summary>
        internal static string FailedGetTerminal {
            get {
                return ResourceManager.GetString("FailedGetTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить подразделениея! Попробуйте позже..
        /// </summary>
        internal static string FailedGetTerminals {
            get {
                return ResourceManager.GetString("FailedGetTerminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить пользователя! Попробуйте позже..
        /// </summary>
        internal static string FailedGetUser {
            get {
                return ResourceManager.GetString("FailedGetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить информаию о пользователе! Попробуйте позже..
        /// </summary>
        internal static string FailedGetUserInfo {
            get {
                return ResourceManager.GetString("FailedGetUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось войти! Попробуйте позже..
        /// </summary>
        internal static string FailedLogin {
            get {
                return ResourceManager.GetString("FailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось зарегистрироваться! Попробуйте позже..
        /// </summary>
        internal static string FailedRegister {
            get {
                return ResourceManager.GetString("FailedRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить конфигурацию! Попробуйте позже..
        /// </summary>
        internal static string FailedSaveConfiguration {
            get {
                return ResourceManager.GetString("FailedSaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить билинг лицо! Попробуйте позже..
        /// </summary>
        internal static string FailedUpdateBillingFace {
            get {
                return ResourceManager.GetString("FailedUpdateBillingFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить бизнес процесс.
        /// </summary>
        internal static string FailedUpdateBusinessProcess {
            get {
                return ResourceManager.GetString("FailedUpdateBusinessProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить контрагента.
        /// </summary>
        internal static string FailedUpdateContractor {
            get {
                return ResourceManager.GetString("FailedUpdateContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить подразделение! Попробуйте позже..
        /// </summary>
        internal static string FailedUpdateDivision {
            get {
                return ResourceManager.GetString("FailedUpdateDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить шаблон! Попробуйте позже..
        /// </summary>
        internal static string FailedUpdateTemplate {
            get {
                return ResourceManager.GetString("FailedUpdateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить пользователя! Попробуйте позже..
        /// </summary>
        internal static string FailedUpdateUser {
            get {
                return ResourceManager.GetString("FailedUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось зарегистрироваться! Введенный ИНН уже используется!.
        /// </summary>
        internal static string InnIsUsed {
            get {
                return ResourceManager.GetString("InnIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти ИНН! Проверьте верность введенных данных..
        /// </summary>
        internal static string InnNotFound {
            get {
                return ResourceManager.GetString("InnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC.LK.BACKEND.
        /// </summary>
        internal static string JWT_Audience {
            get {
                return ResourceManager.GetString("JWT_Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC.LK.CLIENT.
        /// </summary>
        internal static string JWT_Issuer {
            get {
                return ResourceManager.GetString("JWT_Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC.LK.BACKEND.KEY:[akkp1j23j45]1p511l23].
        /// </summary>
        internal static string JWT_Key {
            get {
                return ResourceManager.GetString("JWT_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1440.
        /// </summary>
        internal static string JWT_LifetimeInMinute {
            get {
                return ResourceManager.GetString("JWT_LifetimeInMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось зарегистрироваться! Введенный логин уже используется! Попробуйте восстановить пароль.
        /// </summary>
        internal static string LoginIsUsed {
            get {
                return ResourceManager.GetString("LoginIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось зарегистрировать пользователя! Эта почта уже используется..
        /// </summary>
        internal static string MailIsUsed {
            get {
                return ResourceManager.GetString("MailIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;info&quot;:{},&quot;style&quot;:{},&quot;forms&quot;:{}}.
        /// </summary>
        internal static string NoneConfiguration {
            get {
                return ResourceManager.GetString("NoneConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось зарегистрировать пользователя! Вы не обладаете правами администратора..
        /// </summary>
        internal static string NotEnoughRights {
            get {
                return ResourceManager.GetString("NotEnoughRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить информацию!.
        /// </summary>
        internal static string UpdateNotSuccess {
            get {
                return ResourceManager.GetString("UpdateNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователя не существует в базе данных..
        /// </summary>
        internal static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
    }
}
