// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SC.LK.Infrastructure.Database.Contexts;

#nullable disable

namespace SC.LK.Infrastructure.Database.Migrations
{
    [DbContext(typeof(MethodsConfiguratorContext))]
    partial class MethodsConfiguratorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SC.LK.Application.Domains.Entities.MethodAccessTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("MethodAccessType");
                });

            modelBuilder.Entity("SC.LK.Application.Domains.Entities.MethodWithRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AvailableRoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MethodAccessTypesEntitiesId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("MethodWithRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
